#!/bin/bash

#Colour
font="\e[0m"
blue="\e[34m"
red="\e[91m"
white="\e[33m"
    
echo -e "  ${white}menu${font}  ${red}:  Menampilkan Menu Yang Ada${font}"
echo -e "  ${white}1.${font}    ${red}:  Menambah Pengguna${font}"
echo -e "  ${white}2.${font}    ${red}:  Keluar${font}"
    
read -rp "Sila Memasukkan Nombor Pilihan Anda:" nombor_menu
case $nombor_menu in
1)
    usernew
    ;;
2)
    exit 1
    ;;
*)
echo -e " Sila masukkan nombor yang betul "
esac
    
usernew() {
    usernew
}
