#!/bin/sh
    
echo -e "  ${white}menu${font}    
${red}:  Menampilkan Menu Yang Ada${font}"
echo -e "  ${white}1.${font}    
${red}:  Menambah Pengguna{font}
echo -e "  ${white}2.${font}    
${red}:  Keluar${font}
    
read -rp "${red}Sila${font} ${white}Memasukkan${font} ${red}Nombor Pilihan Anda${font}" nombor_menu
case $nombor_menu in
1)
    usernew
    ;;
2)
    exit 1
    ;;
*)
echo -e "${red} Sila masukkan nombor yang betul ${font}"
esac
    
usernew() {
    usernew
}
